<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>.*((Starting FileMaker Server)|(Import operations started)|(\*\*\* Started consistency check)|(Container Data Transfer started)).*</string>
	<key>foldingStartMarker</key>
	<string>started$</string>
	<key>foldingStopMarker</key>
	<string>(committed|canceled|completed)$</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>FileMaker Log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(started|committed|completed|canceled)</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>match</key>
			<string>===*?$\n?</string>
			<key>name</key>
			<string>meta.separator.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(missing|Unknown Error)\b</string>
			<key>name</key>
			<string>constant.filemaker</string>
		</dict>
		<dict>
			<key>match</key>
			<string>clipboard</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>-[0-9]{4}\t(.*?(?:fp7)|(?:fmp12))\s</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>-[0-9]{4}\s(.*?)\t</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::([0-9]+)::</string>
			<key>name</key>
			<string>entity.name.tag.localname.special.xml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>calculation "</string>
			<key>contentName</key>
			<string>string</string>
			<key>end</key>
			<string>" is </string>
		</dict>
		<dict>
			<key>begin</key>
			<string>Error:\s</string>
			<key>contentName</key>
			<string>string</string>
			<key>end</key>
			<string>[0-9]{4}-[0-9]{2}</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>("|“)</string>
			<key>end</key>
			<string>("|”)</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta</string>
				</dict>
			</dict>
			<key>match</key>
			<string>file (".+?") started</string>
			<key>name</key>
			<string>meta</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.filemaker</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[0-9]{1,4}\t(Item|Table|Function|Field|Script|Layout)</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:&lt;.+?(Missing)&gt;)|(?:is (missing).)|(&lt;unknown&gt;)|(?:\t(Unknown Error):)|(?:\b(Error)\b)|(?:\b(Warning)\b)</string>
			<key>name</key>
			<string></string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[0-9]{4}-[0-9]{2}-[0-9]{2}</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t(Client|Schedule|(?:Opening Database)|(?:Opened Database)|(?:Starting FileMaker Server))\s</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*fmserverd\[[0-9]+\]\t*</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t[^\t]+\t</string>
			<key>name</key>
			<string>storage.type.method</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.fmlog</string>
	<key>uuid</key>
	<string>034E35EE-B4C1-474C-B52E-9B24270FB643</string>
</dict>
</plist>
