<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>.*&lt;:.*?:=.*</string>
	<key>foldingStartMarker</key>
	<string>&lt;:</string>
	<key>foldingStopMarker</key>
	<string>:&gt;</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>FileMaker Hash</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>NOT matching!!! Not sure why.</string>
			<key>name</key>
			<string>constant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#hash_value</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((/*)&lt;\2:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.hash</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.hash</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.tag.hash</string>
			<key>end</key>
			<string>(\2:\2=)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_chars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hash_value</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/*:/*&gt;)</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>hash_value</key>
		<dict>
			<key>begin</key>
			<string>((/*):\2=)</string>
			<key>contentName</key>
			<string>string.hash</string>
			<key>end</key>
			<string>(\2:\2&gt;)</string>
		</dict>
		<key>tag_chars</key>
		<dict>
			<key>match</key>
			<string>(/*&lt;/*:)|(/*:/*&gt;)|(/*:/*=)</string>
			<key>name</key>
			<string>punctuation.definition.tag.hash</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>string.filemaker.hash</string>
	<key>uuid</key>
	<string>E06766B0-3F1B-494C-886E-6CFFEF39FFF0</string>
</dict>
</plist>
